#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("ToDoList.Droid.Resource", IsApplication=true)]

namespace ToDoList.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050001
			public const int ContentLayout = 2131034113;
			
			// aapt resource value: 0x7f050016
			public const int DateText = 2131034134;
			
			// aapt resource value: 0x7f05000a
			public const int DescriptionLabel = 2131034122;
			
			// aapt resource value: 0x7f050015
			public const int DescriptionText = 2131034133;
			
			// aapt resource value: 0x7f050010
			public const int ErrorLabel = 2131034128;
			
			// aapt resource value: 0x7f050002
			public const int LoadLayout = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int LoadProgress = 2131034115;
			
			// aapt resource value: 0x7f05000f
			public const int LoginButton = 2131034127;
			
			// aapt resource value: 0x7f05000c
			public const int LoginInnerLayout = 2131034124;
			
			// aapt resource value: 0x7f05000b
			public const int LoginMainLayout = 2131034123;
			
			// aapt resource value: 0x7f05000e
			public const int PasswordText = 2131034126;
			
			// aapt resource value: 0x7f050011
			public const int RegisterButton = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int RegistrationMainLayout = 2131034130;
			
			// aapt resource value: 0x7f050006
			public const int SplashImage = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int SplashInnerLayout = 2131034117;
			
			// aapt resource value: 0x7f050007
			public const int SplashLabel = 2131034119;
			
			// aapt resource value: 0x7f050004
			public const int SplashMainLayout = 2131034116;
			
			// aapt resource value: 0x7f050017
			public const int TagsText = 2131034135;
			
			// aapt resource value: 0x7f050013
			public const int TaskLayout = 2131034131;
			
			// aapt resource value: 0x7f050018
			public const int TaskList = 2131034136;
			
			// aapt resource value: 0x7f050009
			public const int TitleLabel = 2131034121;
			
			// aapt resource value: 0x7f050014
			public const int TitleText = 2131034132;
			
			// aapt resource value: 0x7f050000
			public const int Toolbar = 2131034112;
			
			// aapt resource value: 0x7f05000d
			public const int UserText = 2131034125;
			
			// aapt resource value: 0x7f050008
			public const int VersionText = 2131034120;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ActivityMain = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ActivitySplash = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int CellTask = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int FragmentLogin = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int FragmentRegistration = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int FragmentTask = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int FragmentTaskList = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
